# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: hoverkraft-tech/compose-action@v2.4.1
      with:
        compose-file: "${{ github.workspace }}/docker-compose.yml"
        down-flags: "--volumes"
        services: |
          ea_api
            ports:
              - "8001:8001"  
          ea_webapp
          ports:
              - "8000:8000" 
    - name: Wait for web app to be ready
      run: |
        for i in {1..30}; do
          if curl -sSf http://localhost:5001/ > /dev/null; then
            echo "Web app is up"
            exit 0
          fi
          sleep 2
        done
        echo "Web app failed to start in time"
        exit 1

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run headless test
      uses: coactions/setup-xvfb@v1.0.1
      env:
        TestSettings__ApplicationUrl: "http://localhost:5001"
      with:
       working-directory: ./EaApplicationTest
       run: dotnet test --no-build --verbosity normal
      continue-on-error: true
          
